server:
  port: 9000

spring:
  application:
    name: cards

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
    profiles:
      active:
        - "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to the loans Microservice"
  contactDetails:
    name: "WJ Boshoff"
    email: "wjbosdev@gmail.com"
  onCallSupport:
    - (066) 7584578