build:
  version: "3.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    hibernate:
    show-sql: true
    sql:
      init:
        mode: always

server:
  port: 8080

accounts:
  message: "Welcome to Bank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@fakemail.com"
  onCallSupport: "(555) 555-1234"
