build:
  version: "3.0"

spring:
  datasource:
    url: jdbc:mysql://accountsdb:3306/accountsdb
    username: root
    password: root
    driver:
      classname: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    sql:
      init:
        mode: always

server:
  port: 8080

accounts:
  message: "Welcome to Bank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@fakemail.com"
  onCallSupport: "(555) 555-1234"
