build:
  version: "1.0"

cards:
  message: "Welcome to Bank cards related prod APIs "
  contactDetails:
    name: "Not WJ Boshoff - Product Owner"
    email: "testuser@fakemail.com"
  onCallSupport:
    - "(453) 392-4829"