build:
  version: "1.0"

spring:
  datasource:
    datasource:
      url: jdbc:mysql://cardsdb:3306/cardsdb
      username: root
      password: root
      driver:
        classname: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      sql:
        init:
          mode: always

server:
  port: 9000

cards:
  message: "Welcome to the loans Microservice"
  contactDetails:
    name: "WJ Boshoff"
    email: "wjbosdev@gmail.com"
  onCallSupport:
    - "(066) 7584578"