build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9000

cards:
  message: "Welcome to the loans Microservice"
  contactDetails:
    name: "WJ Boshoff"
    email: "wjbosdev@gmail.com"
  onCallSupport:
    - "(066) 7584578"