build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loansdb
    username: root
    password: root
  jpa:
    hibernate:
    show-sql: true
    sql:
      init:
        mode: always

server:
  port: 8090

loans:
  message: "Welcome to the loans Microservice"
  contactDetails:
    name: "WJ Boshoff"
    email: "wjbosdev@gmail.com"
  onCallSupport:
    - "(066) 7584578"