build:
  version: "1.0"

loans:
  message: "Welcome to loans related prod APIs "
  contactDetails:
    name: "Not WJ Boshoff - Product Owner"
    email: "testuser@fakemail.com"
  onCallSupport:
    - (453) 392-4829